services:
  - type: web
    name: houseofvenus-astrocalc
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      bash ./install_ephe.sh

    startCommand: >
      gunicorn app:app
      -w 1
      -k gthread --threads 8
      --timeout 120 --graceful-timeout 30
      --keep-alive 15
      --max-requests 1000 --max-requests-jitter 100
      --worker-tmp-dir /dev/shm
      --bind 0.0.0.0:$PORT

    healthCheckPath: /healthz
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: EPHE_FILE_ID
        value: 1luz3NgX1ECrXHh_xw07AHucIyONJ8vGN
      - key: API_KEY              # usata dal plugin WP
        value: your-secret-api-key
      - key: CONTACT_EMAIL        # per User-Agent - Per Nominatim (etichetta UA educata)
        value: admin@houseofvenus.pl # per User-Agent - Per Nominatim (etichetta UA educata)
      - key: UA_SITE # per User-Agent - Per Nominatim (etichetta UA educata)
        value: https://houseofvenus.pl # per User-Agent - Per Nominatim (etichetta UA educata)
      - key: GEOCODER_ORDER # per sciegliere la sequenza che uno vuole dei GEOCODER
        value: nominatim,openmeteo,mapsco,google
      # opzionale se vuoi usare Google Geocoding come 1° provider
      # - key: GOOGLE_MAPS_API_KEY
      #   value: your-google-key


