services:
  - type: web
    name: houseofvenus-astrocalc
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      bash ./install_ephe.sh
    startCommand: gunicorn app:app -w 2 -k gthread --threads 8 --timeout 60 --keep-alive 5 --preload --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: EPHE_FILE_ID
        value: 1luz3NgX1ECrXHh_xw07AHucIyONJ8vGN


